### ISSUE TITLE
调用没反应

### ISSUE THREAD

**Issue by hiroshihuang** [shi-yingyingjiang/nonebot-plugin-yinyu#1]
![Clip_2024-04-25_12-23-17](https://github.com/shi-yingyingjiang/nonebot-plugin-yinyu/assets/164932517/0313d969-f73d-4ffb-b9b8-d2fda01c4c40)
安装好了，输入后没反应，大佬看看是哪里出了问题

**Comment by shi-yingyingjiang** [comment]
如果你是跟着快速上手部署的，大概要加命令起始字符”/“

**Comment by hiroshihuang** [comment]
> 如果你是跟着快速上手部署的，大概要加命令起始字符”/“

![Clip_2024-04-25_13-36-04](https://github.com/shi-yingyingjiang/nonebot-plugin-yinyu/assets/164932517/28d3e6b1-5bd8-4a62-b015-d3bbfccc454c)
我是用插件开发者那个部署的，然后我试了下，好像还是不行

**Comment by hiroshihuang** [comment]
真的是这个，解决了，谢谢大佬

**Comment by hiroshihuang** [comment]
> 如果你是跟着快速上手部署的，大概要加命令起始字符”/“

真的是这个，解决了，谢谢大佬
